pi_serial: pi_serial.c
	gcc pi_serial.c -o pi_serial

pi_multi-thread: pi_multi-thread.c
	gcc pi_multi-thread.c -pthread -o pi_multi-thread

code: code.c
	gcc code.c -o code

clean:
	rm -f pi_multi-thread pi_serial